
##########------------------------------------------------------##########
##########              Project-specific Details                ##########
##########    Check these every time you start a new project    ##########
##########------------------------------------------------------##########

MCU   = atmega328p
SERIAL_PORT = COM9
SERIAL_BAUD = 9600
#UPLOAD_BAUD = 57600 # arduino nano clone needs default overrided
PROGRAMMER_TYPE = arduino

## A directory for common include files and the simple USART library.
## If you move either the current folder or the Library folder, you'll 
##  need to change this path to match.
LIBDIR = ../../libs/avr_lib


## The name of your project (without the .c)
# TARGET = blinkLED
## Or name it automatically after the enclosing directory
## Include the library makefile which has all project non-specific details
include $(LIBDIR)/include.mak
